// Mock data for artifacts
export const artifactsData = [
    {
      id: 1,
      name: "Xe tăng T-54 số hiệu 843",
      description:
        "Xe tăng T-54 số hiệu 843 đã húc đổ cổng Dinh Độc Lập vào trưa ngày 30/4/1975, đánh dấu thời khắc lịch sử của sự kiện giải phóng miền Nam, thống nhất đất nước.",
      image: "/placeholder.svg?height=600&width=800&text=T-54",
      category: "Vũ khí hạng nặng",
      period: "Chiến tranh chống Mỹ",
      year: 1975,
      location: "Khu trưng bày ngoài trời",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 2,
      name: "Máy bay MiG-21 của Anh hùng Phạm Tuân",
      description:
        "Máy bay MiG-21 do Anh hùng Phạm Tuân điều khiển bắn rơi máy bay B-52 của Mỹ trong chiến dịch Điện Biên Phủ trên không năm 1972.",
      image: "/placeholder.svg?height=600&width=800&text=MiG-21",
      category: "Máy bay",
      period: "Chiến tranh chống Mỹ",
      year: 1972,
      location: "Khu trưng bày ngoài trời",
      has3D: false,
      hasAudio: false,
    },
    {
      id: 3,
      name: "Đại bác thần công thời Nguyễn",
      description:
        "Bộ sưu tập đại bác thần công được đúc dưới triều Nguyễn, thế kỷ 19, là vũ khí quan trọng trong việc bảo vệ chủ quyền đất nước thời bấy giờ.",
      image: "/placeholder.svg?height=600&width=800&text=Đại bác",
      category: "Vũ khí hạng nặng",
      period: "Thời Nguyễn",
      year: 1820,
      location: "Khu trưng bày vũ khí",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 4,
      name: "Súng AK-47 của Bộ đội Cụ Hồ",
      description:
        "Súng trường tự động AK-47, vũ khí chủ lực của Quân đội Nhân dân Việt Nam trong các cuộc kháng chiến chống Pháp và chống Mỹ.",
      image: "/placeholder.svg?height=600&width=800&text=AK-47",
      category: "Vũ khí cầm tay",
      period: "Chiến tranh chống Mỹ",
      year: 1960,
      location: "Khu trưng bày vũ khí",
      has3D: false,
      hasAudio: false,
    },
    {
      id: 5,
      name: "Bản đồ chiến dịch Điện Biên Phủ",
      description:
        "Bản đồ chi tiết về chiến dịch Điện Biên Phủ năm 1954, thể hiện vị trí đóng quân, đường hành quân và chiến thuật của quân đội Việt Nam.",
      image: "/placeholder.svg?height=600&width=800&text=Bản đồ",
      category: "Tài liệu",
      period: "Chiến tranh chống Pháp",
      year: 1954,
      location: "Khu trưng bày chiến tranh chống Pháp",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 6,
      name: "Áo bà ba của nữ du kích Nam Bộ",
      description:
        "Bộ trang phục đặc trưng của nữ du kích Nam Bộ trong kháng chiến chống Mỹ, thể hiện tinh thần chiến đấu kiên cường của phụ nữ Việt Nam.",
      image: "/placeholder.svg?height=600&width=800&text=Áo bà ba",
      category: "Trang phục",
      period: "Chiến tranh chống Mỹ",
      year: 1968,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 7,
      name: "Huy hiệu Quyết Thắng",
      description:
        "Huy hiệu Quyết Thắng được trao cho các chiến sĩ có thành tích xuất sắc trong chiến đấu, là biểu tượng của tinh thần quyết tâm giành chiến thắng.",
      image: "/placeholder.svg?height=600&width=800&text=Huy hiệu",
      category: "Huy chương",
      period: "Chiến tranh chống Mỹ",
      year: 1970,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: false,
    },
    {
      id: 8,
      name: "Đèn dầu của chiến sĩ Trường Sơn",
      description:
        "Đèn dầu được sử dụng bởi các chiến sĩ trên đường Trường Sơn huyền thoại, là vật dụng thiết yếu trong điều kiện chiến đấu khó khăn.",
      image: "/placeholder.svg?height=600&width=800&text=Đèn dầu",
      category: "Vật dụng",
      period: "Chiến tranh chống Mỹ",
      year: 1965,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: false,
    },
    {
      id: 9,
      name: "Kiếm của Vua Quang Trung",
      description:
        "Thanh kiếm được cho là của vua Quang Trung - Nguyễn Huệ, người đã lãnh đạo quân Tây Sơn đánh bại 20 vạn quân Thanh trong trận Đống Đa năm 1789.",
      image: "/placeholder.svg?height=600&width=800&text=Kiếm",
      category: "Vũ khí cầm tay",
      period: "Thời Tây Sơn",
      year: 1789,
      location: "Khu trưng bày vũ khí",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 10,
      name: "Trống đồng Đông Sơn",
      description:
        "Trống đồng Đông Sơn, hiện vật tiêu biểu của nền văn hóa Đông Sơn, thể hiện trình độ kỹ thuật đúc đồng cao của người Việt cổ.",
      image: "/placeholder.svg?height=600&width=800&text=Trống đồng",
      category: "Hiện vật văn hóa",
      period: "Văn hóa Đông Sơn",
      year: 1000,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 11,
      name: "Nỏ thần của An Dương Vương",
      description:
        "Mô hình nỏ thần theo truyền thuyết của vua An Dương Vương, vũ khí bí mật giúp bảo vệ Cổ Loa Thành khỏi quân xâm lược.",
      image: "/placeholder.svg?height=600&width=800&text=Nỏ thần",
      category: "Vũ khí cầm tay",
      period: "Âu Lạc",
      year: 1200,
      location: "Khu trưng bày vũ khí",
      has3D: false,
      hasAudio: false,
    },
    {
      id: 12,
      name: "Bản Tuyên ngôn Độc lập năm 1945",
      description:
        "Bản sao Tuyên ngôn Độc lập do Chủ tịch Hồ Chí Minh đọc tại Quảng trường Ba Đình ngày 2/9/1945, khai sinh nước Việt Nam Dân chủ Cộng hòa.",
      image: "/placeholder.svg?height=600&width=800&text=Tuyên ngôn",
      category: "Tài liệu",
      period: "Cách mạng Tháng Tám",
      year: 1945,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 13,
      name: "Xe đạp thồ hàng ra tiền tuyến",
      description:
        "Xe đạp thồ được sử dụng để vận chuyển vũ khí, lương thực và đạn dược ra tiền tuyến trong kháng chiến chống Mỹ.",
      image: "/placeholder.svg?height=600&width=800&text=Xe đạp thồ",
      category: "Phương tiện",
      period: "Chiến tranh chống Mỹ",
      year: 1968,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: false,
    },
    {
      id: 14,
      name: "Máy thu thanh của Đài Tiếng nói Việt Nam",
      description:
        "Máy thu thanh được sử dụng bởi Đài Tiếng nói Việt Nam trong thời kỳ kháng chiến, đóng vai trò quan trọng trong việc truyền tải thông tin.",
      image: "/placeholder.svg?height=600&width=800&text=Máy thu thanh",
      category: "Thiết bị",
      period: "Chiến tranh chống Pháp",
      year: 1950,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 15,
      name: "Quân phục của Đại tướng Võ Nguyên Giáp",
      description:
        "Bộ quân phục của Đại tướng Võ Nguyên Giáp, vị tướng tài ba đã chỉ huy nhiều chiến dịch quan trọng trong lịch sử quân sự Việt Nam.",
      image: "/placeholder.svg?height=600&width=800&text=Quân phục",
      category: "Trang phục",
      period: "Chiến tranh chống Pháp",
      year: 1954,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 16,
      name: "Lá cờ Quyết Thắng trên nóc Dinh Độc Lập",
      description:
        "Lá cờ Quyết Thắng được cắm trên nóc Dinh Độc Lập ngày 30/4/1975, đánh dấu thời khắc lịch sử của sự kiện giải phóng miền Nam.",
      image: "/placeholder.svg?height=600&width=800&text=Cờ Quyết Thắng",
      category: "Cờ hiệu",
      period: "Chiến tranh chống Mỹ",
      year: 1975,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 17,
      name: "Pháo cao xạ 37mm",
      description:
        "Pháo cao xạ 37mm, vũ khí phòng không hiệu quả của Quân đội Nhân dân Việt Nam, đã bắn rơi nhiều máy bay Mỹ trong chiến tranh.",
      image: "/placeholder.svg?height=600&width=800&text=Pháo cao xạ",
      category: "Vũ khí hạng nặng",
      period: "Chiến tranh chống Mỹ",
      year: 1965,
      location: "Khu trưng bày ngoài trời",
      has3D: false,
      hasAudio: false,
    },
    {
      id: 18,
      name: "Bản đồ đường Hồ Chí Minh trên biển",
      description:
        "Bản đồ chi tiết về đường Hồ Chí Minh trên biển, tuyến đường vận chuyển vũ khí và hàng hóa bằng đường biển vào miền Nam trong kháng chiến.",
      image: "/placeholder.svg?height=600&width=800&text=Bản đồ HCM",
      category: "Tài liệu",
      period: "Chiến tranh chống Mỹ",
      year: 1962,
      location: "Khu trưng bày chiến tranh chống Mỹ",
      has3D: false,
      hasAudio: true,
    },
    {
      id: 19,
      name: "Tàu không số",
      description:
        "Mô hình tàu không số, phương tiện vận chuyển quan trọng trên đường Hồ Chí Minh trên biển, góp phần đưa hàng nghìn tấn vũ khí vào chiến trường miền Nam.",
      image: "/placeholder.svg?height=600&width=800&text=Tàu không số",
      category: "Phương tiện",
      period: "Chiến tranh chống Mỹ",
      year: 1962,
      location: "Khu trưng bày chiến tranh chống Mỹ",
      has3D: false,
      hasAudio: false,
    },
    {
      id: 20,
      name: "Bút máy của Chủ tịch Hồ Chí Minh",
      description:
        "Chiếc bút máy Chủ tịch Hồ Chí Minh đã sử dụng để ký nhiều văn kiện quan trọng, trong đó có Tuyên ngôn Độc lập năm 1945.",
      image: "/placeholder.svg?height=600&width=800&text=Bút máy",
      category: "Vật dụng",
      period: "Cách mạng Tháng Tám",
      year: 1945,
      location: "Khu trưng bày hiện vật lịch sử",
      has3D: false,
      hasAudio: true,
    },
  ]
  
  // Categories
  export const categories = [
    { id: "Vũ khí hạng nặng", name: "Vũ khí hạng nặng" },
    { id: "Vũ khí cầm tay", name: "Vũ khí cầm tay" },
    { id: "Máy bay", name: "Máy bay" },
    { id: "Tài liệu", name: "Tài liệu" },
    { id: "Trang phục", name: "Trang phục" },
    { id: "Huy chương", name: "Huy chương" },
    { id: "Vật dụng", name: "Vật dụng" },
    { id: "Hiện vật văn hóa", name: "Hiện vật văn hóa" },
    { id: "Phương tiện", name: "Phương tiện" },
    { id: "Thiết bị", name: "Thiết bị" },
    { id: "Cờ hiệu", name: "Cờ hiệu" },
  ]
  
  // Time periods
  export const periods = [
    { id: "Văn hóa Đông Sơn", name: "Văn hóa Đông Sơn" },
    { id: "Âu Lạc", name: "Âu Lạc" },
    { id: "Thời Tây Sơn", name: "Thời Tây Sơn" },
    { id: "Thời Nguyễn", name: "Thời Nguyễn" },
    { id: "Cách mạng Tháng Tám", name: "Cách mạng Tháng Tám" },
    { id: "Chiến tranh chống Pháp", name: "Chiến tranh chống Pháp" },
    { id: "Chiến tranh chống Mỹ", name: "Chiến tranh chống Mỹ" },
  ]
  
  // Locations
  export const locations = [
    { id: "Khu trưng bày ngoài trời", name: "Khu trưng bày ngoài trời" },
    { id: "Khu trưng bày vũ khí", name: "Khu trưng bày vũ khí" },
    { id: "Khu trưng bày hiện vật lịch sử", name: "Khu trưng bày hiện vật lịch sử" },
    { id: "Khu trưng bày chiến tranh chống Pháp", name: "Khu trưng bày chiến tranh chống Pháp" },
    { id: "Khu trưng bày chiến tranh chống Mỹ", name: "Khu trưng bày chiến tranh chống Mỹ" },
  ]
  
  